# Site settings
title: emfs 
email: william+emfs@tuffbizz.com
description: > # this means to ignore newlines until "baseurl:"
  EMFS is an email based filesystem. Utilizing plain old SMTP and IMAP, EMFS can
  mount any email account (from any provider) as a fully functional filesystem
  capable of storing, indexing, and retrieving files of arbitrary size.
baseurl: "/emfs-frontend/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: fcf634cbe8298176f7c576faed0e500a

# Build settings
markdown: kramdown
